#pragma once


#define ICON_PATH_DIR "img/"
#define ICON_PATH_EXTENSION ".svg"

#define ICON_PATH_APP_ICON ICON_PATH_DIR "icon"   ICON_PATH_EXTENSION
#define ICON_PATH_ABOUT    ICON_PATH_DIR "info"   ICON_PATH_EXTENSION
#define ICON_PATH_CREATE   ICON_PATH_DIR "plus"   ICON_PATH_EXTENSION
#define ICON_PATH_MDONE    ICON_PATH_DIR "tick"   ICON_PATH_EXTENSION
#define ICON_PATH_RENAME   ICON_PATH_DIR "pencil" ICON_PATH_EXTENSION
#define ICON_PATH_DELETE   ICON_PATH_DIR "cross"  ICON_PATH_EXTENSION
#define ICON_PATH_MCOLOR   ICON_PATH_DIR "colors" ICON_PATH_EXTENSION
#define ICON_PATH_BOARDS   ICON_PATH_DIR "boards" ICON_PATH_EXTENSION
#define ICON_PATH_LIST     ICON_PATH_DIR "list"   ICON_PATH_EXTENSION
